# Generated by Django 5.2.2 on 2026-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_email_sent_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
