# Generated by Django 5.2.2 on 2026-05-27 08:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('area_city', models.CharField(db_index=True, max_length=120)),
                ('game_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], db_index=True, default='mixed', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('payment_note', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('game_date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show'), ('removed', 'Removed')], db_index=True, default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_by_host', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at',),
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['area_city', 'game_date', 'skill_level'], name='games_game_area_ci_03868f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'game_date'], name='games_game_status_f2200a_idx'),
        ),
        migrations.AddIndex(
            model_name='gameparticipant',
            index=models.Index(fields=['game', 'status'], name='games_gamep_game_id_5e1002_idx'),
        ),
        migrations.AddIndex(
            model_name='gameparticipant',
            index=models.Index(fields=['user', 'status'], name='games_gamep_user_id_824fa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameparticipant',
            unique_together={('game', 'user')},
        ),
    ]
