# Generated by Django 5.2.2 on 2026-04-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('game_reminder', 'Game Reminder'), ('join_confirmation', 'Join Confirmation'), ('system', 'System')], db_index=True, max_length=30),
        ),
    ]
