# Generated by Django 5.2.2 on 2026-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('game_reminder', 'Game Reminder'), ('join_confirmation', 'Join Confirmation'), ('join_request', 'Join Request'), ('system', 'System')], db_index=True, max_length=30),
        ),
    ]
